run:
  skip-files:
    - zetasql/lexer/acttab.go
    - zetasql/lexer/lexer.go
    - zetasql/lexer/transitiontable.go
    - zetasql/parser/action.go
    - zetasql/parser/actiontable.go
    - zetasql/parser/context.go
    - zetasql/parser/gototable.go
    - zetasql/parser/productionstable.go

linters:
  enable:
    - asciicheck
    - bidichk
    - cyclop
    - deadcode
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - goconst
    - gocritic
    - godox
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - structcheck
    - testpackage
    - typecheck
    - unused
    - varcheck
    - wsl

linters-settings:

  lll:
    line-length: 80

  cyclop:
    max-complexity: 30