// Code generated by gocc; DO NOT EDIT.

package token

import (
	"bytes"
	"fmt"
	"strconv"
	"unicode/utf8"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset  int
	Line    int
	Column  int
	Context Context
}

func (p Pos) String() string {
	// If the context provides a filename, provide a human-readable File:Line:Column representation.
	switch src := p.Context.(type) {
	case Sourcer:
		return fmt.Sprintf("%s:%d:%d", src.Source(), p.Line, p.Column)
	default:
		return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
	}
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

// Equals returns returns true if the token Type and Lit are matches.
func (t *Token) Equals(rhs interface{}) bool {
	switch rhsT := rhs.(type) {
	case *Token:
		return t == rhsT || (t.Type == rhsT.Type && bytes.Equal(t.Lit, rhsT.Lit))
	default:
		return false
	}
}

// CharLiteralValue returns the string value of the char literal.
func (t *Token) CharLiteralValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

// Float32Value returns the float32 value of the token or an error if the token literal does not
// denote a valid float32.
func (t *Token) Float32Value() (float32, error) {
	if v, err := strconv.ParseFloat(string(t.Lit), 32); err != nil {
		return 0, err
	} else {
		return float32(v), nil
	}
}

// Float64Value returns the float64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Float64Value() (float64, error) {
	return strconv.ParseFloat(string(t.Lit), 64)
}

// IDValue returns the string representation of an identifier token.
func (t *Token) IDValue() string {
	return string(t.Lit)
}

// Int32Value returns the int32 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int32Value() (int32, error) {
	if v, err := strconv.ParseInt(string(t.Lit), 10, 64); err != nil {
		return 0, err
	} else {
		return int32(v), nil
	}
}

// Int64Value returns the int64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int64Value() (int64, error) {
	return strconv.ParseInt(string(t.Lit), 10, 64)
}

// UTF8Rune decodes the UTF8 rune in the token literal. It returns utf8.RuneError if
// the token literal contains an invalid rune.
func (t *Token) UTF8Rune() (rune, error) {
	r, _ := utf8.DecodeRune(t.Lit)
	if r == utf8.RuneError {
		err := fmt.Errorf("Invalid rune")
		return r, err
	}
	return r, nil
}

// StringValue returns the string value of the token literal.
func (t *Token) StringValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		";",
		"empty",
		"select",
		",",
		"as",
		"*",
		"from",
		"where",
		"join",
		"unnest",
		"(",
		")",
		"with",
		"offset",
		"order",
		"by",
		"asc",
		"desc",
		"nulls",
		"first",
		"last",
		"limit",
		"partition",
		"between",
		"and",
		"rows",
		"range",
		"unbounded",
		"preceding",
		"following",
		"current",
		"row",
		"interval",
		"to",
		"array",
		"<",
		">",
		"struct",
		"or",
		"not",
		"|",
		"^",
		"&",
		"[",
		"]",
		".",
		"like",
		"in",
		"is",
		"+",
		"-",
		"~",
		"/",
		"||",
		"<<",
		">>",
		"integer_literal",
		"string_literal",
		"floating_point_literal",
		"bytes_literal",
		"boolean_literal",
		"null",
		"json",
		"identifier",
		"date",
		"numeric_or_decimal",
		"extract",
		"tablesample",
		"percent",
		"weight",
		"repeatable",
		"cast",
		"@",
		"format",
		"at",
		"time",
		"zone",
		"on",
		"using",
		"cross",
		"full",
		"inner",
		"left",
		"right",
		"outer",
		"distinct",
		"ignore",
		"respect",
		"over",
		"safe_cast",
		"end",
		"else",
		"case",
		"when",
		"then",
		"=",
		"!=",
		"<>",
		"<=",
		">=",
		"all",
		"bignumeric_or_bigdecimal",
		"comment",
		"datetime",
		"except",
		"group",
		"having",
		"illegal_character",
		"intersect",
		"missing_whitespace_float_and_alias",
		"missing_whitespace_int_and_alias",
		"qualify",
		"replace",
		"timestamp",
		"union",
		"unterminated_bytes_literal",
		"unterminated_comment",
		"unterminated_escaped_identifier",
		"unterminated_raw_bytes_literal",
		"unterminated_raw_string_literal",
		"unterminated_string_literal",
		"unterminated_triple_quoted_bytes_literal",
		"unterminated_triple_quoted_raw_bytes_literal",
		"unterminated_triple_quoted_raw_string_literal",
		"unterminated_triple_quoted_string_literal",
		"window",
	},

	idMap: map[string]Type{
		"INVALID":                            0,
		"$":                                  1,
		";":                                  2,
		"empty":                              3,
		"select":                             4,
		",":                                  5,
		"as":                                 6,
		"*":                                  7,
		"from":                               8,
		"where":                              9,
		"join":                               10,
		"unnest":                             11,
		"(":                                  12,
		")":                                  13,
		"with":                               14,
		"offset":                             15,
		"order":                              16,
		"by":                                 17,
		"asc":                                18,
		"desc":                               19,
		"nulls":                              20,
		"first":                              21,
		"last":                               22,
		"limit":                              23,
		"partition":                          24,
		"between":                            25,
		"and":                                26,
		"rows":                               27,
		"range":                              28,
		"unbounded":                          29,
		"preceding":                          30,
		"following":                          31,
		"current":                            32,
		"row":                                33,
		"interval":                           34,
		"to":                                 35,
		"array":                              36,
		"<":                                  37,
		">":                                  38,
		"struct":                             39,
		"or":                                 40,
		"not":                                41,
		"|":                                  42,
		"^":                                  43,
		"&":                                  44,
		"[":                                  45,
		"]":                                  46,
		".":                                  47,
		"like":                               48,
		"in":                                 49,
		"is":                                 50,
		"+":                                  51,
		"-":                                  52,
		"~":                                  53,
		"/":                                  54,
		"||":                                 55,
		"<<":                                 56,
		">>":                                 57,
		"integer_literal":                    58,
		"string_literal":                     59,
		"floating_point_literal":             60,
		"bytes_literal":                      61,
		"boolean_literal":                    62,
		"null":                               63,
		"json":                               64,
		"identifier":                         65,
		"date":                               66,
		"numeric_or_decimal":                 67,
		"extract":                            68,
		"tablesample":                        69,
		"percent":                            70,
		"weight":                             71,
		"repeatable":                         72,
		"cast":                               73,
		"@":                                  74,
		"format":                             75,
		"at":                                 76,
		"time":                               77,
		"zone":                               78,
		"on":                                 79,
		"using":                              80,
		"cross":                              81,
		"full":                               82,
		"inner":                              83,
		"left":                               84,
		"right":                              85,
		"outer":                              86,
		"distinct":                           87,
		"ignore":                             88,
		"respect":                            89,
		"over":                               90,
		"safe_cast":                          91,
		"end":                                92,
		"else":                               93,
		"case":                               94,
		"when":                               95,
		"then":                               96,
		"=":                                  97,
		"!=":                                 98,
		"<>":                                 99,
		"<=":                                 100,
		">=":                                 101,
		"all":                                102,
		"bignumeric_or_bigdecimal":           103,
		"comment":                            104,
		"datetime":                           105,
		"except":                             106,
		"group":                              107,
		"having":                             108,
		"illegal_character":                  109,
		"intersect":                          110,
		"missing_whitespace_float_and_alias": 111,
		"missing_whitespace_int_and_alias":   112,
		"qualify":                            113,
		"replace":                            114,
		"timestamp":                          115,
		"union":                              116,
		"unterminated_bytes_literal":         117,
		"unterminated_comment":               118,
		"unterminated_escaped_identifier":    119,
		"unterminated_raw_bytes_literal":     120,
		"unterminated_raw_string_literal":    121,
		"unterminated_string_literal":        122,
		"unterminated_triple_quoted_bytes_literal":      123,
		"unterminated_triple_quoted_raw_bytes_literal":  124,
		"unterminated_triple_quoted_raw_string_literal": 125,
		"unterminated_triple_quoted_string_literal":     126,
		"window": 127,
	},
}
