// Code generated by gocc; DO NOT EDIT.

package token

import (
	"bytes"
	"fmt"
	"strconv"
	"unicode/utf8"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset  int
	Line    int
	Column  int
	Context Context
}

func (p Pos) String() string {
	// If the context provides a filename, provide a human-readable File:Line:Column representation.
	switch src := p.Context.(type) {
	case Sourcer:
		return fmt.Sprintf("%s:%d:%d", src.Source(), p.Line, p.Column)
	default:
		return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
	}
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

// Equals returns returns true if the token Type and Lit are matches.
func (t *Token) Equals(rhs interface{}) bool {
	switch rhsT := rhs.(type) {
	case *Token:
		return t == rhsT || (t.Type == rhsT.Type && bytes.Equal(t.Lit, rhsT.Lit))
	default:
		return false
	}
}

// CharLiteralValue returns the string value of the char literal.
func (t *Token) CharLiteralValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

// Float32Value returns the float32 value of the token or an error if the token literal does not
// denote a valid float32.
func (t *Token) Float32Value() (float32, error) {
	if v, err := strconv.ParseFloat(string(t.Lit), 32); err != nil {
		return 0, err
	} else {
		return float32(v), nil
	}
}

// Float64Value returns the float64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Float64Value() (float64, error) {
	return strconv.ParseFloat(string(t.Lit), 64)
}

// IDValue returns the string representation of an identifier token.
func (t *Token) IDValue() string {
	return string(t.Lit)
}

// Int32Value returns the int32 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int32Value() (int32, error) {
	if v, err := strconv.ParseInt(string(t.Lit), 10, 64); err != nil {
		return 0, err
	} else {
		return int32(v), nil
	}
}

// Int64Value returns the int64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int64Value() (int64, error) {
	return strconv.ParseInt(string(t.Lit), 10, 64)
}

// UTF8Rune decodes the UTF8 rune in the token literal. It returns utf8.RuneError if
// the token literal contains an invalid rune.
func (t *Token) UTF8Rune() (rune, error) {
	r, _ := utf8.DecodeRune(t.Lit)
	if r == utf8.RuneError {
		err := fmt.Errorf("Invalid rune")
		return r, err
	}
	return r, nil
}

// StringValue returns the string value of the token literal.
func (t *Token) StringValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		";",
		"empty",
		"(",
		")",
		"select",
		",",
		"as",
		".*",
		"*",
		"except",
		"replace",
		"with",
		"where",
		"all",
		"distinct",
		"struct",
		"from",
		"join",
		"group",
		"by",
		"rollup",
		"having",
		"qualify",
		"window",
		"unnest",
		"offset",
		"order",
		"asc",
		"desc",
		"nulls",
		"first",
		"last",
		"limit",
		"partition",
		"between",
		"and",
		"rows",
		"range",
		"unbounded",
		"preceding",
		"following",
		"current",
		"row",
		"interval",
		"to",
		"array",
		"<",
		">",
		"or",
		"not",
		"|",
		"^",
		"&",
		"[",
		"]",
		".",
		"like",
		"in",
		"is",
		"+",
		"-",
		"~",
		"/",
		"||",
		"<<",
		">>",
		"integer_literal",
		"string_literal",
		"floating_point_literal",
		"bytes_literal",
		"boolean_literal",
		"null",
		"numeric",
		"decimal",
		"bignumeric",
		"bigdecimal",
		"date",
		"datetime",
		"time",
		"timestamp",
		"json",
		"identifier",
		"extract",
		"exists",
		"tablesample",
		"percent",
		"weight",
		"repeatable",
		"cast",
		"@",
		"format",
		"at",
		"zone",
		"on",
		"using",
		"cross",
		"full",
		"inner",
		"left",
		"right",
		"outer",
		"ignore",
		"respect",
		"over",
		"safe_cast",
		"end",
		"else",
		"case",
		"when",
		"then",
		"=",
		"!=",
		"<>",
		"<=",
		">=",
		"comment",
		"illegal_character",
		"intersect",
		"missing_whitespace_float_and_alias",
		"missing_whitespace_hex_and_alias",
		"missing_whitespace_int_and_alias",
		"proto",
		"union",
		"unterminated_bytes_literal",
		"unterminated_comment",
		"unterminated_escaped_identifier",
		"unterminated_raw_bytes_literal",
		"unterminated_raw_string_literal",
		"unterminated_string_literal",
		"unterminated_triple_quoted_bytes_literal",
		"unterminated_triple_quoted_raw_bytes_literal",
		"unterminated_triple_quoted_raw_string_literal",
		"unterminated_triple_quoted_string_literal",
	},

	idMap: map[string]Type{
		"INVALID":                            0,
		"$":                                  1,
		";":                                  2,
		"empty":                              3,
		"(":                                  4,
		")":                                  5,
		"select":                             6,
		",":                                  7,
		"as":                                 8,
		".*":                                 9,
		"*":                                  10,
		"except":                             11,
		"replace":                            12,
		"with":                               13,
		"where":                              14,
		"all":                                15,
		"distinct":                           16,
		"struct":                             17,
		"from":                               18,
		"join":                               19,
		"group":                              20,
		"by":                                 21,
		"rollup":                             22,
		"having":                             23,
		"qualify":                            24,
		"window":                             25,
		"unnest":                             26,
		"offset":                             27,
		"order":                              28,
		"asc":                                29,
		"desc":                               30,
		"nulls":                              31,
		"first":                              32,
		"last":                               33,
		"limit":                              34,
		"partition":                          35,
		"between":                            36,
		"and":                                37,
		"rows":                               38,
		"range":                              39,
		"unbounded":                          40,
		"preceding":                          41,
		"following":                          42,
		"current":                            43,
		"row":                                44,
		"interval":                           45,
		"to":                                 46,
		"array":                              47,
		"<":                                  48,
		">":                                  49,
		"or":                                 50,
		"not":                                51,
		"|":                                  52,
		"^":                                  53,
		"&":                                  54,
		"[":                                  55,
		"]":                                  56,
		".":                                  57,
		"like":                               58,
		"in":                                 59,
		"is":                                 60,
		"+":                                  61,
		"-":                                  62,
		"~":                                  63,
		"/":                                  64,
		"||":                                 65,
		"<<":                                 66,
		">>":                                 67,
		"integer_literal":                    68,
		"string_literal":                     69,
		"floating_point_literal":             70,
		"bytes_literal":                      71,
		"boolean_literal":                    72,
		"null":                               73,
		"numeric":                            74,
		"decimal":                            75,
		"bignumeric":                         76,
		"bigdecimal":                         77,
		"date":                               78,
		"datetime":                           79,
		"time":                               80,
		"timestamp":                          81,
		"json":                               82,
		"identifier":                         83,
		"extract":                            84,
		"exists":                             85,
		"tablesample":                        86,
		"percent":                            87,
		"weight":                             88,
		"repeatable":                         89,
		"cast":                               90,
		"@":                                  91,
		"format":                             92,
		"at":                                 93,
		"zone":                               94,
		"on":                                 95,
		"using":                              96,
		"cross":                              97,
		"full":                               98,
		"inner":                              99,
		"left":                               100,
		"right":                              101,
		"outer":                              102,
		"ignore":                             103,
		"respect":                            104,
		"over":                               105,
		"safe_cast":                          106,
		"end":                                107,
		"else":                               108,
		"case":                               109,
		"when":                               110,
		"then":                               111,
		"=":                                  112,
		"!=":                                 113,
		"<>":                                 114,
		"<=":                                 115,
		">=":                                 116,
		"comment":                            117,
		"illegal_character":                  118,
		"intersect":                          119,
		"missing_whitespace_float_and_alias": 120,
		"missing_whitespace_hex_and_alias":   121,
		"missing_whitespace_int_and_alias":   122,
		"proto":                              123,
		"union":                              124,
		"unterminated_bytes_literal":         125,
		"unterminated_comment":               126,
		"unterminated_escaped_identifier":    127,
		"unterminated_raw_bytes_literal":     128,
		"unterminated_raw_string_literal":    129,
		"unterminated_string_literal":        130,
		"unterminated_triple_quoted_bytes_literal":      131,
		"unterminated_triple_quoted_raw_bytes_literal":  132,
		"unterminated_triple_quoted_raw_string_literal": 133,
		"unterminated_triple_quoted_string_literal":     134,
	},
}
